<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
content="width=device-width, initial-scale=1.0">
  <title>Data Analyst Portfolio</title>
  <link rel="stylesheet" href+"style.css">
  </head>
  <body>
  <header>
    <h1>welcome to My Data Analyst Portfolio</h1>
      <p>Hi, I'm MEREDITH MOTUNRAYO OLUWASEYI. i turn data into insights.</p>
        </header>
        <section id="about">
          <h2>About Me</h2>
          <p>I am a data analyst with expertise in Excel,SQL,Powerbi,and Python. My passion is in uncovering insights from data and delivering value to businesses.</p>
            </section>
            <section id="projects">
            <h2>Projects</h2>
            <u1>
              <1i>
                <h3>Project Title 1</h3>
                <p>Brief descripiton of another project with relevant details. </p>
                    <a href="link-to-your-project">View Project</a>
                        </1i>
                      </ul>
                    </section>
                  <section id="skills">
                      <h2>Skills and tools</h2>
                      <p>Python, SQl, Powerbi, Excel<lp>
                      <section>
                      <section id="contact">
                        <h2>Contact Me</h2>
                        <p>Email: oluwaseyimeredith123@gmail.com</p>
                        <p>Linkedin: <a href="linkedin.com/in/meredith-motunrayo-oluwaseyi-382183337">LinkedIn Profile</a></p>
                          </section>
                          </body>
                          </htlm>
              
  
